{% set name = "hepdata-validator" %}
{% set version = "0.3.6" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hepdata_validator-{{ version }}.tar.gz
  sha256: e57b97f83509c81d579ccbbd4cdd515043ba32aa1d8543bf31a36a19dcf08fbb

build:
  entry_points:
    - hepdata-validate=hepdata_validator.cli:validate
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pytest
    - pip
  run:
    - python >={{ python_min }}
    - click
    - jsonschema
    - packaging
    - pyyaml >=5.4.1
    - requests

test:
  imports:
    - hepdata_validator
  commands:
    - pip check
    - hepdata-validate --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hepdata/hepdata-validator
  summary: JSON schema and validation code for HEPData submissions
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - GraemeWatt
    - matthewfeickert
